module_name: "rvc"

# NOTE: Frequencies will be converted to an integer number of ms for a delay
# TODO: DELETE COMMENTING AFTER EDITING - change bucket frequencies to 250Hz, 50 Hz, and 10Hz

buckets:
    high_frequency_ADCs:
        frequency_hz: 50
        parameters:
            rvcBrakePressureRear_psi:
                ADC: ADC1_IN4
                sensor: brake_pressure_sensor_rife
                samples_buffered: 1
            rvcCurrentSensor_A:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcRadWaterTempIn_C:
                ADC: ADC1_IN11
                sensor: temp_sensor
                samples_buffered: 1
            rvcShockPosRearLeft_mm: #Volt Sense 3
                ADC: ADC1_IN0
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            rvcShockPosRearRight_mm: #Volt Sense 4
                ADC: ADC1_IN5
                sensor: linear_pos_sensor_50
                samples_buffered: 1

    low_frequency:
        frequency_hz: 10
        parameters:
            rvcSdcStatus8:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcSdcStatus9:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1

        # BSPD Faults
            rvcBspdRunawayFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcBspdInputFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcBspdFaultActive_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcBspdFaultLatched_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
            # RVC Controlled Outputs
            rvcCoolantFanPowerF_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcCoolantFanPowerR_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcCoolantPumpPowerF_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcCoolantPumpPowerR_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcDrsEnabled_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcBrakeBias_percent:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1             
            rvcBrakeLightOn_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcVehicleBuzzerOn_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            
            rvcBrakeTempRearRight_C: #Volt Sense 2
                ADC: ADC1_IN6
                sensor: brake_temp_sensor
                samples_buffered: 1
            rvcRearRideHeight_mm:
                ADC: ADC1_IN9
                sensor: full_raw_voltage_sensor # TODO make ride height sensor in gophersense
                samples_buffered: 1
            rvcRadWaterTempOut_C:
                ADC: ADC1_IN10
                sensor: temp_sensor
                samples_buffered: 1
            rvcCurrentSensorLow_A:
                ADC: ADC1_IN8
                sensor: current_sensor_1
                samples_buffered: 1
            rvcCurrentSensorHigh_A:
                ADC: ADC1_IN3
                sensor: current_sensor_2
                samples_buffered: 1
            rvcCurrentSensorStatus_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvc5V1Overcurrent_Count:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcEfuse5V1Fault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcEfuse5V2Fault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcEfuse12VFault_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            rvcEfuse12VCurrent_A:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1